### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [tchlux/tlux#3]
I suggest adding topics such as `nearest-neighbors`, `nonlinear-regression`, `regex` in the About section at https://github.com/tchlux/tlux

**Comment by tchlux** [comment]
Thanks for the feedback! If you ever want to try out the python+fortran codes for your own problems or work let me know. I'd love to get feedback on usability and am happy to help. The nonlinear regressor for approximation (also does classification problems) is a project I'm trying to advance.
